# Numpy Arrays

In [1]:
# Main way to use numpy

In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
# Matrix

In [9]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# A lot faster and a lot simpler numpy arrays

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.linspace(0,1000,10)

array([   0.        ,  111.11111111,  222.22222222,  333.33333333,
        444.44444444,  555.55555556,  666.66666667,  777.77777778,
        888.88888889, 1000.        ])

In [18]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(4,4)

array([[0.94293094, 0.21801032, 0.50653077, 0.43187751],
       [0.16733559, 0.01532699, 0.51507348, 0.55871212],
       [0.71848676, 0.38810587, 0.41294466, 0.19055135],
       [0.11391964, 0.00882134, 0.76022636, 0.77602883]])

In [20]:
np.random.randn(2,2)

array([[ 0.96720059,  0.45020336],
       [ 0.55942352, -0.32132626]])

In [21]:
np.random.randint(1,10)

3

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ramarr = np.random.randint(0,50,10)

In [37]:
ramarr

array([40, 45, 17, 27, 27, 30,  5, 27, 22, 36])

In [38]:
# Reshape returns an array with the same data as the shape

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ramarr

array([27, 17, 39, 12, 18,  9, 11, 28, 29,  6])

In [45]:
ramarr.max()

39

In [46]:
ramarr.min()

6

In [47]:
ramarr.argmax()

2

In [48]:
ramarr.argmin()

9

In [49]:
arr.shape

(25,)

In [50]:
ramarr.shape

(10,)

In [51]:
arr.reshape(5,5).shape

(5, 5)

In [52]:
arr.dtype

dtype('int32')