# Numpy Arrays

In [1]:
# Main way to use numpy

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
# Matrix

In [8]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# A lot faster and a lot simpler numpy arrays

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [26]:
np.linspace(0,1000,10)

array([   0.        ,  111.11111111,  222.22222222,  333.33333333,
        444.44444444,  555.55555556,  666.66666667,  777.77777778,
        888.88888889, 1000.        ])

In [28]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
np.random.rand(4,4)

array([[0.98444097, 0.65085606, 0.18233202, 0.34440997],
       [0.16775458, 0.56094974, 0.09275987, 0.53593176],
       [0.34091408, 0.19466371, 0.36537331, 0.28059439],
       [0.96779483, 0.2184451 , 0.01463398, 0.30001601]])

In [34]:
np.random.randn(2,2)

array([[ 0.26261691, -0.74802231],
       [ 0.703572  ,  1.13864556]])

In [36]:
np.random.randint(1,10)

array([8, 4, 2])

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ramarr = np.random.randint(0,50,10)

In [40]:
ramarr

array([27, 17, 39, 12, 18,  9, 11, 28, 29,  6])

In [41]:
# Reshape returns an array with the same data as the shape

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ramarr

array([27, 17, 39, 12, 18,  9, 11, 28, 29,  6])

In [45]:
ramarr.max()

39

In [46]:
ramarr.min()

6

In [47]:
ramarr.argmax()

2

In [48]:
ramarr.argmin()

9

In [49]:
arr.shape

(25,)

In [50]:
ramarr.shape

(10,)

In [51]:
arr.reshape(5,5).shape

(5, 5)