In [1]:
import numpy as np

In [9]:
arr = np.arange(5)

In [10]:
arr

array([0, 1, 2, 3, 4])

In [11]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [41]:
arr = np.array([float("{:0.2f}".format(x**0.5)) for x in range(1,100)])

In [42]:
arr

array([1.  , 1.41, 1.73, 2.  , 2.24, 2.45, 2.65, 2.83, 3.  , 3.16, 3.32,
       3.46, 3.61, 3.74, 3.87, 4.  , 4.12, 4.24, 4.36, 4.47, 4.58, 4.69,
       4.8 , 4.9 , 5.  , 5.1 , 5.2 , 5.29, 5.39, 5.48, 5.57, 5.66, 5.74,
       5.83, 5.92, 6.  , 6.08, 6.16, 6.24, 6.32, 6.4 , 6.48, 6.56, 6.63,
       6.71, 6.78, 6.86, 6.93, 7.  , 7.07, 7.14, 7.21, 7.28, 7.35, 7.42,
       7.48, 7.55, 7.62, 7.68, 7.75, 7.81, 7.87, 7.94, 8.  , 8.06, 8.12,
       8.19, 8.25, 8.31, 8.37, 8.43, 8.49, 8.54, 8.6 , 8.66, 8.72, 8.77,
       8.83, 8.89, 8.94, 9.  , 9.06, 9.11, 9.17, 9.22, 9.27, 9.33, 9.38,
       9.43, 9.49, 9.54, 9.59, 9.64, 9.7 , 9.75, 9.8 , 9.85, 9.9 , 9.95])

## NUMPY INDEXING AND SELECTION

In [43]:
arr = np.arange(0,11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[4]

4

In [50]:
arr [::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [51]:
arr[0:6:2]

array([0, 2, 4])

In [52]:
arr[:6:2]

array([0, 2, 4])

In [53]:
arr[5::2]

array([5, 7, 9])

In [55]:
arr[5:] # Get's beyond 5. In our list, the 5th index is the number 4

array([ 5,  6,  7,  8,  9, 10])

#### How they differ?

In [56]:
arr[0:5] = 100

In [57]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

##### They can broadcast new values like the above or do slices like the below

In [58]:
slice_of_arr = arr[0:6]

In [59]:
slice_of_arr[:] = 99

In [60]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# ATTENTION!!

##### NUMPY WILL BROADCAST CHANGES. 
<p> Like the above, we've created a slice and made a change. That change was replicated in the original array </p>
<p> This is because numpy wants to avoid memory issues when dealing with big arrays </p>
<p> We need to be explicit if we want to create a copy and not a reference to the original array </p>

In [71]:
arr_copy = arr.copy()

In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_copy[0:6] = 100

In [75]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [76]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [77]:
del arr_copy ## Getting rid of it from memory

# INDEXING 2D ARRAY (MATRIX)

In [78]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [79]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
# Double Bracket Format
# [ROW][COLUMN]
arr_2d[0][0]

5

In [83]:
arr_2d[0]

array([ 5, 10, 15])

In [84]:
arr_2d[0][2]

15

In [85]:
arr_2d[1][1]

25

# COMMA SINGLE BRACKET NOTATION

In [87]:
arr_2d[1,2]
#is the same as arr_2s[1][2]

30

In [88]:
# What if I wanted chunks of this array

In [91]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [93]:
# Remeber the format [row][column]
arr_2d[:2,1:]

## I want everyting up to row 2 (not inclusive) and everything from column 1 onwards (inclusive)

array([[10, 15],
       [25, 30]])

In [94]:
arr_2d[2:,1:]

array([[40, 45]])

In [101]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [119]:
super_arr = np.array([["{a:0.2f}".format(a=x/2) for x in range(0,5)], 
            ["{a:0.2f}".format(a=x**3) for x in range(0,5)],
            ["{a:0.2f}".format(a=x*2) for x in range(0,5)],
            ["{a:0.2f}".format(a=x**0.5) for x in range(0,5)]])

In [120]:
super_arr.shape

(4, 5)

In [121]:
super_arr.dtype

dtype('<U5')

In [127]:
super_arr

array([['0.00', '0.50', '1.00', '1.50', '2.00'],
       ['0.00', '1.00', '8.00', '27.00', '64.00'],
       ['0.00', '2.00', '4.00', '6.00', '8.00'],
       ['0.00', '1.00', '1.41', '1.73', '2.00']], dtype='<U5')

In [128]:
super_arr[2:,:3]

array([['0.00', '2.00', '4.00'],
       ['0.00', '1.00', '1.41']], dtype='<U5')

# MORE IMPORTANT: Conditional Selection

In [130]:
arr = np.arange(1,11)

In [131]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [136]:
bool_arr = arr > 3

In [138]:
arr[bool_arr] #only returns instances where that is true

array([ 4,  5,  6,  7,  8,  9, 10])

In [139]:
arr[arr>7]

array([ 8,  9, 10])

In [140]:
arr[arr<3]

array([1, 2])

# EXERCISE

In [154]:
arr_2d = np.arange(50).reshape(5,10)

In [155]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [152]:
bool_array = arr_2d[arr_2d**0.5 > 6] 

In [160]:
arr_2d[:3,7:]

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29]])